

const music = [

  {text:"(Organic) machinery", status : {end: true}},
  {text:"A very small object – Its centre ", status : {end: true}},
  {text:"Abandon desire", status : {end: true}},
  {text:"Abandon normal instructions", status : {end: true}},
  {text:"Abandon normal instruments", status : {end: true}},
  {text:"Adding on All that happens is good", status : {end: true}},
  {text:"Always give yourself credit for having more than personality", status : {end: true}},
  {text:"Always the first steps", status : {end: true}},
  {text:"Back up a few steps. What else could you have done? Be less critical more often", status : {end: true}},
  {text:"Bridges – build – burn Call your mother and ask her what to do.", status : {end: true}},
  {text:"Change ambiguities to specifics", status : {end: true}},
  {text:"Change specifics to ambiguities", status : {end: true}},
  {text:"Children singing Children speaking", status : {end: true}},
  {text:"Children’s voices – speaking – singing Consider transitions", status : {end: true}},
  {text:"Consult other sources: promising", status : {end: true}},
  {text:"Consult other sources: unpromising", status : {end: true}},
  {text:"Credibility of Intentions Define an area as “safe” and use it as an anchor", status : {end: true}},
  {text:"Describe the landscape in which this belongs. ", status : {end: true}},
  {text:"Destroy nothing", status : {end: true}},
  {text:"Destroy the most important thing ", status : {end: true}},
  {text:"Disconnect from desire", status : {end: true}},
  {text:"Discover your formulas and abandon them", status : {end: true}},
  {text:"Display your talent", status : {end: true}},
  {text:"Distorting time", status : {end: true}},
  {text:"Do something sudden, destructive and unpredictable", status : {end: true}},
  {text:"Do the last thing first Don’t avoid what is easy", status : {end: true}},
  {text:"Faced with a choice, do both Feedback recordings into an acoustic situation", status : {end: true}},
{text:"First work alone, then work in unusual pairs", status : {end: true}},


{text:"From nothing to more than", status : {end: true}},
{text:"nothing", status : {end: true}},
{text:"Give way to your worst", status : {end: true}},
{text:"impulse Go inside. Shut the door.", status : {end: true}},
{text:"Go outside. Shut the door.", status : {end: true}},
{text:"Go to an extreme, move", status : {end: true}},
{text:"back to a more comfortable", status : {end: true}},
{text:"place", status : {end: true}},
{text:"Go, make a demo about it Honour thy error as a", status : {end: true}},
{text:"hidden intention", status : {end: true}},
{text:"How would someone else do", status : {end: true}},
{text:"it?", status : {end: true}},
{text:"How would you explain this", status : {end: true}},
{text:"to your parents?", status : {end: true}},
{text:"Humanize something free of", status : {end: true}},
{text:"error", status : {end: true}},
{text:"Humility of Intentions", status : {end: true}},
{text:"Idiot glee Imagine a caterpillar", status : {end: true}},
{text:"moving", status : {end: true}},
{text:"Imagine the music as a", status : {end: true}},
{text:"moving chain or caterpillar", status : {end: true}},
{text:"Imagine the music as a", status : {end: true}},
{text:"series of disconnected events", status : {end: true}},
{text:"Instead of changing the", status : {end: true}},
{text:"thing, change the world", status : {end: true}},
{text:"around it.", status : {end: true}},
{text:"Intentions – credibility of –", status : {end: true}},
{text:"nobility of – humility of", status : {end: true}},
{text:"Into the impossible Is the style right?", status : {end: true}},
{text:"Is the tuning appropriate? Is the tuning intonation", status : {end: true}},
{text:"correct?", status : {end: true}},
{text:"Is there something missing? It is simply a matter or", status : {end: true}},
{text:"work", status : {end: true}},
{text:"Its centre Krawall!", status : {end: true}},
{text:"Left channel, right channel,", status : {end: true}},
{text:"centre channel", status : {end: true}},
{text:"List the qualities it has.", status : {end: true}},
{text:"List those you’d like.", status : {end: true}},
{text:"Listen in total darkness, or", status : {end: true}},
{text:"in a very large room, very", status : {end: true}},
{text:"quietly", status : {end: true}},
{text:"Look closely at the most", status : {end: true}},
{text:"embarrassing details and", status : {end: true}},
{text:"amplify.", status : {end: true}},
{text:"Lowest common", status : {end: true}},
{text:"denominator check – single", status : {end: true}},
{text:"beat – single note – single", status : {end: true}},
{text:"riff", status : {end: true}},
{text:"Magnify the most difficult", status : {end: true}},
{text:"details", status : {end: true}},
{text:"Make a blank valuable by", status : {end: true}},
{text:"putting it in an exquisite", status : {end: true}},
{text:"frame", status : {end: true}},
{text:"Make it more sensual", status : {end: true}},
{text:"Make what’s perfect more", status : {end: true}},
{text:"human", status : {end: true}},
{text:"Mechanize something", status : {end: true}},
{text:"idiosyncratic", status : {end: true}},
{text:"Move towards the", status : {end: true}},
{text:"unimportant Nobility of Intentions", status : {end: true}},
{text:"Once the search has begun,", status : {end: true}},
{text:"something will be found Only a part, not the whole", status : {end: true}},
{text:"Pae White’s non-blank", status : {end: true}},
{text:"graphic metacard", status : {end: true}},
{text:"Pay attention to", status : {end: true}},
{text:"distractions", status : {end: true}},
{text:"Picture of a man spotlighted Remove a restriction", status : {end: true}},
{text:"Remove the middle, extend", status : {end: true}},
{text:"the edges Retrace your steps", status : {end: true}},
{text:"Short circuit (example; a", status : {end: true}},
{text:"man eating peas with the", status : {end: true}},
{text:"idea that they will improve", status : {end: true}},
{text:"his virility shovels them", status : {end: true}},
{text:"straight into his lap)", status : {end: true}},
{text:"Shut the door and listen", status : {end: true}},
{text:"from outside", status : {end: true}},
{text:"Slow preparation, fast", status : {end: true}},
{text:"execution", status : {end: true}},
{text:"State the problem in words", status : {end: true}},
{text:"as clearly as possible", status : {end: true}},
{text:"Steal a solution. Take a walk and study the", status : {end: true}},
{text:"architecture", status : {end: true}},
{text:"Take away as much mystery", status : {end: true}},
{text:"as possible. What is left?", status : {end: true}},
{text:"Take away the important", status : {end: true}},
{text:"parts", status : {end: true}},
{text:"Tape your mouth Think – inside the work –", status : {end: true}},
{text:"outside the work", status : {end: true}},
{text:"Try faking it Use “unqualified” people.", status : {end: true}},
{text:"Use an unacceptable color Use cliches", status : {end: true}},
{text:"Use something nearby as a", status : {end: true}},
{text:"model", status : {end: true}},
{text:"Use your own ideas", status : {end: true}},
{text:"Voice your suspicions What are the sections", status : {end: true}},
{text:"sections of?", status : {end: true}},
{text:"What are you really", status : {end: true}},
{text:"thinking about just now?", status : {end: true}},
{text:"What context would look", status : {end: true}},
{text:"right?", status : {end: true}},
{text:"What do you do? Now,", status : {end: true}},
{text:"what do you do best? What else is this like?", status : {end: true}},
{text:"What is the simplest", status : {end: true}},
{text:"solution?", status : {end: true}},
{text:"What most recently", status : {end: true}},
{text:"impressed you? How is it", status : {end: true}},
{text:"similar? What can you", status : {end: true}},
{text:"learn from it? What could", status : {end: true}},
{text:"you take from it?", status : {end: true}},
{text:"What to increase? What to", status : {end: true}},
{text:"reduce? What to maintain?", status : {end: true}},
{text:"What were the branch", status : {end: true}},
{text:"points in the evolution of", status : {end: true}},
{text:"this entity", status : {end: true}},
{text:"What were you really", status : {end: true}},
{text:"thinking about just now?", status : {end: true}},
{text:"Incorporate", status : {end: true}},
{text:"What would make this", status : {end: true}},
{text:"really successful?", status : {end: true}},
{text:"When is it for? Who is it", status : {end: true}},
{text:"for? Where is the edge?", status : {end: true}},
{text:"Which parts can be", status : {end: true}},
{text:"grouped?", status : {end: true}},
{text:"Who would make this really", status : {end: true}},
{text:"successful?", status : {end: true}},
{text:"Would anyone want it? Your mistake was a hidden intention", status : {end: true}}

]
