'use strict';

const words = [
  {text:"Change the order", status : {end: true}},
  {text:"Reveal the hidden concept ", status : {end: true}},
  {text:"Why are you doing that ?", status : {end: true}},
  {text:"Deliver now", status : {end: true}},
  {text:"Denormalize", status : {end: true}},
  {text:"Think nano", status : {end: true}},
  {text:"Think big", status : {end: true}},
  {text:"Refine, again", status : {end: true}},
  {text:"Consult the one you are working for", status : {end: true}},
  {text:"Draw the model", status : {end: true}},
  {text:"Not incrementally but iteratively", status : {end: true}},
  {text:"Do you have a plan ?", status : {end: true}},
  {text:"You’re an artist", status : {end: true}},
  {text:"Where is the context switch ?", status : {end: true}},
  {text:"What is the ultimate purpose ?", status : {end: true}},
  {text:"Be less dogmatic", status : {end: true}},
  {text:"Is it beautiful ?", status : {end: true}},
  {text:"Is it fair ?", status : {end: true}},
  {text:"Is it right ?", status : {end: true}},
  {text:"Consider links", status : {end: true}},
  {text:"Go out for a walk", status : {end: true}},
  {text:"Abandon nobility of Intentions", status : {end: true}},
  {text:"Listen to children", status : {end: true}},
  {text:"Courage", status : {end: true}},
  {text:"Abandon desire ", status : {end: true}},
  {text:"Always the first steps ", status : {end: true}},
  {text:"Back up a few steps. What else could you have done? ", status : {end: true}},
  {text:"Be less critical more often ", status : {end: true}},
  {text:"Change ambiguities to specifics ", status : {end: true}},
  {text:"Credibility of Intentions ", status : {end: true}},
  {text:"Define an area as “safe” and use it as an anchor", status : {end: true}},
  {text:"Describe the landscape in which this belongs. ", status : {end: true}},
  {text:"Destroy the most important thing ", status : {end: true}},
  {text:"Disconnect from desire ", status : {end: true}},
  {text:"Do the last thing first ", status : {end: true}},
  {text:"Don’t avoid what is easy ", status : {end: true}},
  {text:"Faced with a choice, do both ", status : {end: true}},
  {text:"First work alone, then work in unusual pairs. ", status : {end: true}},
  {text:"Go inside. Shut the door. ", status : {end: true}},
  {text:"Go to an extreme, move back to a more comfortable place ", status : {end: true}},
  {text:"Go, make a demo about it ", status : {end: true}},
  {text:"Honour the error as a hidden intention ", status : {end: true}},
  {text:"How would someone else do it? ", status : {end: true}},
  {text:"How would you explain this to your parents? ", status : {end: true}},
  {text:"Humility of Intentions ", status : {end: true}},
  {text:"Instead of changing the thing, change the world around it. ", status : {end: true}},
  {text:"Into the impossible ", status : {end: true}},
  {text:"Is the style right? ", status : {end: true}},
  {text:"Is the tuning appropriate? ", status : {end: true}},
  {text:"Is there something missing? ", status : {end: true}},
  {text:"It is simply a matter or work ", status : {end: true}},
  {text:"List the qualities it has. ", status : {end: true}},
  {text:"List those you’d like. ", status : {end: true}},
  {text:"Magnify the most difficult details ", status : {end: true}},
  {text:"Move towards the unimportant ", status : {end: true}},
  {text:"Nobility of Intentions ", status : {end: true}},
  {text:"Abandon nobility of Intentions", status : {end: true}},
  {text:"Once the search has begun, something will be found ", status : {end: true}},
  {text:"Only a part, not the whole ", status : {end: true}},
  {text:"Remove a restriction ", status : {end: true}},
  {text:"Remove the middle, extend the edges ", status : {end: true}},
  {text:"Retrace your steps ", status : {end: true}},
  {text:"Slow preparation, fast execution ", status : {end: true}},
  {text:"State the problem in words as clearly as possible ", status : {end: true}},
  {text:"Steal a solution", status : {end: true}},
  {text:"Take a walk and study the architecture ", status : {end: true}},
  {text:"What is left? ", status : {end: true}},
  {text:"Use your own ideas ", status : {end: true}},
  {text:"Voice your suspicions ", status : {end: true}},
  {text:"What are the sections sections of? ", status : {end: true}},
  {text:"What are you really thinking about just now? ", status : {end: true}},
  {text:"What context would look right? ", status : {end: true}},
  {text:"What do you do? Now, what do you do best? ", status : {end: true}},
  {text:"What else is this like? ", status : {end: true}},
  {text:"What is the simplest solution? ", status : {end: true}},
  {text:"What most recently impressed you? How is it similar? What can you learn from it? What could you take from it? ", status : {end: true}},
  {text:"What to increase? What to reduce? What to maintain? ", status : {end: true}},
  {text:"What were the branch points in the evolution of this entity ", status : {end: true}},
  {text:"What were you really thinking about just now? Incorporate ", status : {end: true}},
  {text:"What would make this really successful? ", status : {end: true}},
  {text:"When is it for? Who is it for? ", status : {end: true}},
  {text:"Where is the edge? ", status : {end: true}},
  {text:"Which parts can be grouped? ", status : {end: true}},
  {text:"Who would make this really successful? ", status : {end: true}},
  {text:"Would anyone want it? ", status : {end: true}},
  {text:"Your mistake was a hidden intention", status : {end: true}},
  {text:"Cut a vital connection", status : {end: true}}
];

module.exports = function getAWord() {
  var randomNum = Math.floor(Math.random() * words.length);
  return words[randomNum];
};
